# Generated by Django 5.2.1 on 2025-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_watchlist', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
